"""Baseline monthly-peak prose fixture for narrative quality regression tests."""

NARRATIVE_QUALITY_BIRTH_INPUT = {
    "birth_date": "1984-08-26",
    "birth_time": "19:20",
    "birthplace": "Tokyo",
    "latitude": 35.8078,
    "longitude": 139.7241,
    "timezone_offset": 9,
    "year": 2026,
    "month": 7,
}

BASELINE_JULY_2026_PERIODS = {
    "general_health": [
        {
            "dates": ("2026-07-01", "2026-07-06", "2026-07-04"),
            "activation": 7.0,
            "caution": 7.0,
            "tone": "mixed",
            "title": "一般・健康の動きが出やすい",
            "summary": "T 火星 と N 太陽 の90度により、心身の状態や生活リズムに変化が出やすい時期です。",
            "description": "体調、睡眠、集中力、生活ペースのどこかに動きが出やすく、無理なく調整するための大枠ルールです。",
            "caution_text": "疲れや違和感を無視せず、休息と予定調整を優先すること。",
            "factors": ("MARS SUN 90°", "MARS MARS 180°", "JUPITER ASC 120°", "NEPTUNE MARS 120°"),
        },
        {
            "dates": ("2026-07-17", "2026-07-23", "2026-07-21"),
            "activation": 8.0,
            "caution": 0.0,
            "tone": "active",
            "title": "心身のペースを整える時期",
            "summary": "太陽がネイタルの心身のペースに無理のない後押しを作り、意志と活力に意識が向きやすい流れです。",
            "description": "太陽の動きが心身のペースを刺激します。日々の反応を確かめながら、今の状態に合う予定と休み方へ整えることで、この時期を活かせます。",
            "caution_text": "一時的な気分や勢いだけで予定を増やさず、疲れが残らない進め方を選んでください。",
            "factors": ("SUN ASC 120°", "JUPITER MARS 120°", "MARS-SATURN 60°", "SUN ソーラー12H入座"),
        },
        {
            "dates": ("2026-07-24", "2026-07-28", "2026-07-27"),
            "activation": 9.2,
            "caution": 2.2,
            "tone": "review",
            "title": "一般・健康の動きが出やすい",
            "summary": "土星のステーションにより、心身の状態や生活リズムに変化が出やすい時期です。",
            "description": "体調、睡眠、集中力、生活ペースのどこかに動きが出やすく、無理なく調整するための大枠ルールです。",
            "caution_text": "疲れや違和感を無視せず、休息と予定調整を優先すること。",
            "factors": ("SATURN留", "SUN MARS 120°", "JUPITER MARS 120°", "SUN-NEPTUNE 120°"),
        },
    ],
    "work": [
        {
            "dates": ("2026-07-01", "2026-07-06", "2026-07-02"),
            "activation": 14.0,
            "caution": 9.0,
            "tone": "mixed",
            "title": "仕事の動きが出やすい",
            "summary": "T 火星 と N 太陽 の90度により、役割、実務、評価、連絡に動きが出やすい時期です。",
            "description": "仕事上の立場、作業量、発信、調整事項のどこかが動きやすくなる大枠ルールです。",
            "caution_text": "急ぎすぎず、確認と優先順位づけを先に行うこと。",
            "factors": ("MARS SUN 90°", "MARS MARS 180°", "MARS JUPITER 150°", "JUPITER MC 150°"),
        },
        {
            "dates": ("2026-07-08", "2026-07-10", "2026-07-10"),
            "activation": 12.4,
            "caution": 4.0,
            "tone": "mixed",
            "title": "仕事の動きが出やすい",
            "summary": "T 金星 と N ASC の150度により、役割、実務、評価、連絡に動きが出やすい時期です。",
            "description": "仕事上の立場、作業量、発信、調整事項のどこかが動きやすくなる大枠ルールです。",
            "caution_text": "急ぎすぎず、確認と優先順位づけを先に行うこと。",
            "factors": ("VENUS ASC 150°", "MARS MERCURY 90°", "JUPITER JUPITER 150°", "VENUS MC 120°"),
        },
        {
            "dates": ("2026-07-17", "2026-07-23", "2026-07-21"),
            "activation": 11.0,
            "caution": 2.0,
            "tone": "mixed",
            "title": "仕事の動きが出やすい",
            "summary": "T 太陽 と N MC の150度により、役割、実務、評価、連絡に動きが出やすい時期です。",
            "description": "仕事上の立場、作業量、発信、調整事項のどこかが動きやすくなる大枠ルールです。",
            "caution_text": "急ぎすぎず、確認と優先順位づけを先に行うこと。",
            "factors": ("SUN MC 150°", "JUPITER JUPITER 150°", "SUN ASC 120°", "VENUS SATURN 60°"),
        },
    ],
    "love": [
        {
            "dates": ("2026-07-08", "2026-07-10", "2026-07-10"),
            "activation": 12.4,
            "caution": 4.0,
            "tone": "mixed",
            "title": "恋愛・対人が動きやすい",
            "summary": "T 金星 と N ASC の150度により、好意、会話、距離感、関係性に動きが出やすい時期です。",
            "description": "恋愛や対人関係の接点、温度、見直し、親密さのどこかが動きやすくなる大枠ルールです。",
            "caution_text": "期待や不安だけで判断せず、相手との距離感を確認すること。",
            "factors": ("VENUS ASC 150°", "MARS MERCURY 90°", "JUPITER JUPITER 150°", "VENUS ネイタル6H入座"),
        },
        {
            "dates": ("2026-07-12", "2026-07-15", "2026-07-14"),
            "activation": 13.0,
            "caution": 6.0,
            "tone": "mixed",
            "title": "惹かれ合いと衝突",
            "summary": "強い引力と温度差が同時に出やすい月",
            "description": "恋愛の動きは出やすい一方で欲求やペースの違いも目立ちやすくなります",
            "caution_text": "勢いで言い切らず相手の境界線を尊重すること",
            "factors": ("VENUS MARS 90°", "JUPITER JUPITER 150°", "SUN VENUS 60°", "VENUS JUPITER 120°"),
        },
        {
            "dates": ("2026-07-17", "2026-07-23", "2026-07-23"),
            "activation": 10.4,
            "caution": 0.0,
            "tone": "mixed",
            "title": "恋愛・対人が動きやすい",
            "summary": "T 木星 と N 木星 の150度により、好意、会話、距離感、関係性に動きが出やすい時期です。",
            "description": "恋愛や対人関係の接点、温度、見直し、親密さのどこかが動きやすくなる大枠ルールです。",
            "caution_text": "期待や不安だけで判断せず、相手との距離感を確認すること。",
            "factors": ("JUPITER JUPITER 150°", "SUN ASC 120°", "JUPITER MARS 120°", "SUN ネイタル5H入座"),
        },
    ],
    "money": [
        {
            "dates": ("2026-07-12", "2026-07-15", "2026-07-14"),
            "activation": 13.0,
            "caution": 6.0,
            "tone": "mixed",
            "title": "金運が動きやすい",
            "summary": "T 金星 と N 火星 の90度により、収入、支出、契約、資産管理に動きが出やすい時期です。",
            "description": "お金の入口、出口、契約、共有財産、予算見直しのどこかが動きやすくなる大枠ルールです。",
            "caution_text": "勢いで決めず、金額、期限、条件を確認すること。",
            "factors": ("VENUS MARS 90°", "MARS SATURN 150°", "JUPITER JUPITER 150°", "SUN VENUS 60°"),
        },
        {
            "dates": ("2026-07-24", "2026-07-25", "2026-07-25"),
            "activation": 9.25,
            "caution": 2.0,
            "tone": "mixed",
            "title": "金運が動きやすい",
            "summary": "T 太陽 と N 木星 の150度により、収入、支出、契約、資産管理に動きが出やすい時期です。",
            "description": "お金の入口、出口、契約、共有財産、予算見直しのどこかが動きやすくなる大枠ルールです。",
            "caution_text": "勢いで決めず、金額、期限、条件を確認すること。",
            "factors": ("SUN JUPITER 150°", "JUPITER MARS 120°", "MERCURY順行化", "MERCURY-VENUS 60°"),
        },
        {
            "dates": ("2026-07-27", "2026-07-28", "2026-07-27"),
            "activation": 10.7,
            "caution": 5.2,
            "tone": "review",
            "title": "金運が動きやすい",
            "summary": "土星のステーションにより、収入、支出、契約、資産管理に動きが出やすい時期です。",
            "description": "お金の入口、出口、契約、共有財産、予算見直しのどこかが動きやすくなる大枠ルールです。",
            "caution_text": "勢いで決めず、金額、期限、条件を確認すること。",
            "factors": ("SATURN留", "SUN MARS 120°", "MARS-VENUS 90°"),
        },
    ],
}
